"""
Export trained SAC model weights to C arrays for MCU deployment.

Usage:
    python export_weights.py --model models/hardware_final --output sac_weights.h

Generates a self-contained C header with:
  - All weight matrices and bias vectors
  - Forward pass function
  - Observation builder
  - Full voltage pipeline (deadzone, clip, proportional catch)
"""

import argparse
import numpy as np
import torch
from stable_baselines3 import SAC
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3.common.vec_env import DummyVecEnv


def extract_actor_weights(model_path: str, include_prev_voltage: bool = True):
    """Extract weight matrices and biases from SAC actor network."""

    class HardwareShapeEnv(gym.Env):
        def __init__(self):
            obs_dim = 7 if include_prev_voltage else 6
            self.observation_space = spaces.Box(
                low=-1.0, high=1.0, shape=(obs_dim,), dtype=np.float32
            )
            self.action_space = spaces.Box(
                low=-1.0, high=1.0, shape=(1,), dtype=np.float32
            )
        def reset(self, **kwargs): return np.zeros(self.observation_space.shape, dtype=np.float32), {}
        def step(self, action): return np.zeros(self.observation_space.shape, dtype=np.float32), 0.0, False, False, {}

    _dummy_env = DummyVecEnv([lambda: HardwareShapeEnv()])
    model = SAC.load(model_path.replace('.zip', ''), env=_dummy_env, device="cpu")
    actor = model.policy.actor

    layers = []

    # Extract hidden layers from latent_pi
    for i, layer in enumerate(actor.latent_pi):
        if hasattr(layer, 'weight'):
            w = layer.weight.detach().cpu().numpy()
            b = layer.bias.detach().cpu().numpy()
            layers.append((f"hidden_{len(layers)}", w, b))
            print(f"  Hidden layer {len(layers)-1}: weight {w.shape}, bias {b.shape}")

    # Extract output (mu) layer
    if hasattr(actor.mu, 'weight'):
        w_mu = actor.mu.weight.detach().cpu().numpy()
        b_mu = actor.mu.bias.detach().cpu().numpy()
    else:
        # When use_sde=True, actor.mu is typically a nn.Sequential
        w_mu = actor.mu[0].weight.detach().cpu().numpy()
        b_mu = actor.mu[0].bias.detach().cpu().numpy()

    layers.append(("mu", w_mu, b_mu))
    print(f"  Output (mu) layer: weight {w_mu.shape}, bias {b_mu.shape}")

    return layers


def array_to_c(name: str, arr: np.ndarray) -> str:
    """Convert numpy array to C array initializer."""
    flat = arr.flatten()
    # Format in rows of 8 for readability
    lines = []
    for i in range(0, len(flat), 8):
        chunk = flat[i:i+8]
        line = ", ".join(f"{v: .8f}f" for v in chunk)
        lines.append(f"    {line}")
    values = ",\n".join(lines)

    if arr.ndim == 1:
        return f"static const float {name}[{arr.shape[0]}] = {{\n{values}\n}};"
    elif arr.ndim == 2:
        return f"// Shape: ({arr.shape[0]}, {arr.shape[1]}) — stored row-major\nstatic const float {name}[{arr.shape[0] * arr.shape[1]}] = {{\n{values}\n}};"
    return ""


def generate_header(layers, output_path: str, include_prev_voltage: bool,
                    rl_vcap: float, rl_voltage_limit: float, rl_angle_deg: float,
                    safe_angle: float, resume_angle_rad: float,
                    deadzone: float, threshold: float, vcap: float):
    """Generate complete C header file."""

    obs_dim = 7 if include_prev_voltage else 6
    hidden_sizes = [w.shape[0] for name, w, b in layers[:-1]]
    
    print(f"\n  Architecture: {obs_dim} -> {' -> '.join(str(s) for s in hidden_sizes)} -> 1")
    print(f"  Total parameters: {sum(w.size + b.size for _, w, b in layers)}")

    lines = []
    lines.append("/*")
    lines.append(" * SAC Actor Network Weights — Auto-generated by export_weights.py")
    lines.append(f" * Architecture: {obs_dim} -> {' -> '.join(str(s) for s in hidden_sizes)} -> 1 (tanh)")
    lines.append(f" * Total parameters: {sum(w.size + b.size for _, w, b in layers)}")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef SAC_WEIGHTS_H")
    lines.append("#define SAC_WEIGHTS_H")
    lines.append("")
    lines.append("#include <math.h>")
    lines.append("")
    lines.append("// ============================================================")
    lines.append("// Constants")
    lines.append("// ============================================================")
    lines.append("")
    lines.append(f"#define SAC_OBS_DIM        {obs_dim}")
    lines.append(f"#define SAC_NUM_HIDDEN     {len(hidden_sizes)}")
    for i, hs in enumerate(hidden_sizes):
        lines.append(f"#define SAC_HIDDEN_{i}_SIZE {hs}")
    lines.append(f"#define SAC_MAX_HIDDEN     {max(hidden_sizes)}")
    lines.append("")
    lines.append(f"#define RL_VCAP            {rl_vcap:.1f}f")
    lines.append(f"#define RL_VOLTAGE_LIMIT   {rl_voltage_limit:.1f}f")
    lines.append(f"#define RL_ANGLE_RAD       {np.radians(rl_angle_deg):.6f}f")
    lines.append(f"#define SAFE_ANGLE         {safe_angle:.4f}f")
    lines.append(f"#define RESUME_ANGLE       {resume_angle_rad:.6f}f")
    lines.append(f"#define DEADZONE_VAL       {deadzone:.2f}f")
    lines.append(f"#define DEADZONE_THRESH    {threshold:.2f}f")
    lines.append(f"#define PROP_VCAP          {vcap:.1f}f")
    lines.append(f"#define VEL_NORM_PEND      15.0f")
    lines.append(f"#define VEL_NORM_ARM       25.0f")
    lines.append("")
    lines.append("// Proportional gains")
    lines.append(f"#define K1 {-4.4681 * 0.25:.6f}f")
    lines.append(f"#define K2 {-1.6210 * 0.50:.6f}f")
    lines.append(f"#define K3 {-39.5037 * 0.75:.6f}f")
    lines.append(f"#define K4 {-5.0402 * 0.60:.6f}f")
    lines.append(f"#define K5 {-0.4387 * 0.50:.6f}f")
    lines.append("")

    # Write weight arrays
    lines.append("// ============================================================")
    lines.append("// Network Weights")
    lines.append("// ============================================================")
    lines.append("")

    for name, w, b in layers:
        lines.append(array_to_c(f"w_{name}", w))
        lines.append("")
        lines.append(array_to_c(f"b_{name}", b))
        lines.append("")

    # Write inference functions
    lines.append("// ============================================================")
    lines.append("// Inference Functions")
    lines.append("// ============================================================")
    lines.append("")

    # ReLU
    lines.append("static inline float sac_relu(float x) {")
    lines.append("    return x > 0.0f ? x : 0.0f;")
    lines.append("}")
    lines.append("")

    # Clamp
    lines.append("static inline float sac_clamp(float x, float lo, float hi) {")
    lines.append("    if (x < lo) return lo;")
    lines.append("    if (x > hi) return hi;")
    lines.append("    return x;")
    lines.append("}")
    lines.append("")

    # Build observation
    lines.append("/*")
    lines.append(" * Build the observation vector from raw sensor readings.")
    lines.append(" * pend_pos: pendulum angle (rad, 0 = upright)")
    lines.append(" * arm_pos:  arm angle (rad)")
    lines.append(" * pend_vel: pendulum angular velocity (rad/s)")
    lines.append(" * arm_vel:  arm angular velocity (rad/s)")
    lines.append(" * last_voltage: voltage applied in previous step")
    lines.append(" */")
    lines.append(f"static void sac_build_obs(float obs[SAC_OBS_DIM],")
    lines.append(f"                          float pend_pos, float arm_pos,")
    lines.append(f"                          float pend_vel, float arm_vel,")
    lines.append(f"                          float last_voltage) {{")
    lines.append(f"    obs[0] = cosf(pend_pos);")
    lines.append(f"    obs[1] = sinf(pend_pos);")
    lines.append(f"    obs[2] = cosf(arm_pos);")
    lines.append(f"    obs[3] = sinf(arm_pos);")
    lines.append(f"    obs[4] = pend_vel / VEL_NORM_PEND;")
    lines.append(f"    obs[5] = arm_vel / VEL_NORM_ARM;")
    if include_prev_voltage:
        lines.append(f"    obs[6] = sac_clamp(last_voltage / RL_VCAP, -1.0f, 1.0f);")
    lines.append("}")
    lines.append("")

    # Forward pass — generic for any 2-hidden-layer architecture
    lines.append("/*")
    lines.append(" * Run SAC actor forward pass.")
    lines.append(" * Returns action in [-1, 1] (tanh-squashed).")
    lines.append(" */")
    lines.append(f"static float sac_forward(const float obs[SAC_OBS_DIM]) {{")

    # We'll generate explicit code for each layer for maximum speed (no loops over layer configs)
    # Layer 0: obs -> hidden_0
    h0_size = hidden_sizes[0]
    lines.append(f"    float h0[{h0_size}];")
    lines.append(f"    for (int i = 0; i < {h0_size}; i++) {{")
    lines.append(f"        float sum = b_hidden_0[i];")
    lines.append(f"        for (int j = 0; j < SAC_OBS_DIM; j++) {{")
    lines.append(f"            sum += w_hidden_0[i * SAC_OBS_DIM + j] * obs[j];")
    lines.append(f"        }}")
    lines.append(f"        h0[i] = sac_relu(sum);")
    lines.append(f"    }}")
    lines.append("")

    if len(hidden_sizes) >= 2:
        h1_size = hidden_sizes[1]
        lines.append(f"    float h1[{h1_size}];")
        lines.append(f"    for (int i = 0; i < {h1_size}; i++) {{")
        lines.append(f"        float sum = b_hidden_1[i];")
        lines.append(f"        for (int j = 0; j < {h0_size}; j++) {{")
        lines.append(f"            sum += w_hidden_1[i * {h0_size} + j] * h0[j];")
        lines.append(f"        }}")
        lines.append(f"        h1[i] = sac_relu(sum);")
        lines.append(f"    }}")
        lines.append("")
        last_hidden_name = "h1"
        last_hidden_size = h1_size
    else:
        last_hidden_name = "h0"
        last_hidden_size = h0_size

    # Output layer: last_hidden -> mu (1 output)
    lines.append(f"    float mu = b_mu[0];")
    lines.append(f"    for (int j = 0; j < {last_hidden_size}; j++) {{")
    lines.append(f"        mu += w_mu[j] * {last_hidden_name}[j];")
    lines.append(f"    }}")
    lines.append("")
    lines.append(f"    return tanhf(mu);")
    lines.append("}")
    lines.append("")

    # Deadzone model
    lines.append("/*")
    lines.append(" * Apply motor deadzone compensation.")
    lines.append(" */")
    lines.append("static float sac_deadzone(float voltage) {")
    lines.append("    if (voltage > DEADZONE_THRESH) {")
    lines.append("        voltage += DEADZONE_VAL;")
    lines.append("    } else if (voltage < -DEADZONE_THRESH) {")
    lines.append("        voltage -= DEADZONE_VAL;")
    lines.append("    } else {")
    lines.append("        voltage = 0.0f;")
    lines.append("    }")
    lines.append(f"    return sac_clamp(voltage, -PROP_VCAP, PROP_VCAP);")
    lines.append("}")
    lines.append("")

    # Proportional controller
    lines.append("/*")
    lines.append(" * Proportional catch controller.")
    lines.append(" */")
    lines.append("static float proportional_voltage(float arm_pos, float arm_vel,")
    lines.append("                                   float pend_pos, float pend_vel,")
    lines.append("                                   float last_voltage) {")
    lines.append("    float u = -(K1 * arm_pos + K2 * arm_vel + K3 * pend_pos + K4 * pend_vel + K5 * last_voltage);")
    lines.append("    u = sac_clamp(u, -PROP_VCAP, PROP_VCAP);")
    lines.append("    return sac_deadzone(u);")
    lines.append("}")
    lines.append("")

    # Full pipeline
    lines.append("/*")
    lines.append(" * Full control pipeline: sensor data -> voltage.")
    lines.append(" * Call this every control loop iteration.")
    lines.append(" *")
    lines.append(" * Returns the voltage to apply to the motor.")
    lines.append(" * Sets *controller to 0 for SAC, 1 for Proportional, 2 for FALLEN.")
    lines.append(" */")
    lines.append("static float sac_control_step(float pend_pos, float arm_pos,")
    lines.append("                              float pend_vel, float arm_vel,")
    lines.append("                              float last_voltage, int *controller) {")
    lines.append("")
    lines.append("    // Wrap pend_pos to [-pi, pi]")
    lines.append("    pend_pos = fmodf(pend_pos + (float)M_PI, 2.0f * (float)M_PI) - (float)M_PI;")
    lines.append("")
    lines.append("    float abs_pend = fabsf(pend_pos);")
    lines.append("")
    lines.append("    // Safety cutoff")
    lines.append("    if (abs_pend > SAFE_ANGLE) {")
    lines.append("        *controller = 2;  // FALLEN")
    lines.append("        return 0.0f;")
    lines.append("    }")
    lines.append("")
    lines.append("    float voltage;")
    lines.append("")
    lines.append("    if (abs_pend < RL_ANGLE_RAD) {")
    lines.append("        // SAC control")
    lines.append("        *controller = 0;")
    lines.append(f"        float obs[SAC_OBS_DIM];")
    lines.append("        sac_build_obs(obs, pend_pos, arm_pos, pend_vel, arm_vel, last_voltage);")
    lines.append("        float action = sac_forward(obs);")
    lines.append("        voltage = action * RL_VCAP;")
    lines.append("        voltage = sac_clamp(voltage, -RL_VOLTAGE_LIMIT, RL_VOLTAGE_LIMIT);")
    lines.append("        voltage = sac_deadzone(voltage);")
    lines.append("    } else {")
    lines.append("        // Proportional catch")
    lines.append("        *controller = 1;")
    lines.append("        voltage = proportional_voltage(arm_pos, arm_vel, pend_pos, pend_vel, last_voltage);")
    lines.append("    }")
    lines.append("")
    lines.append("    return voltage;")
    lines.append("}")
    lines.append("")
    lines.append("#endif // SAC_WEIGHTS_H")
    lines.append("")

    with open(output_path, 'w') as f:
        f.write("\n".join(lines))

    print(f"\n✓ Header written to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="Export SAC weights to C header")
    parser.add_argument('--model', required=True, help='Path to trained SAC model')
    parser.add_argument('--output', default='sac_weights.h', help='Output C header path')
    parser.add_argument('--rl-vcap', type=float, default=12.0, help='RL voltage cap (must match training)')
    parser.add_argument('--rl-voltage-limit', type=float, default=12.0, help='RL voltage hard limit')
    parser.add_argument('--rl-angle', type=float, default=4.0, help='RL angle boundary in degrees')
    parser.add_argument('--safe-angle', type=float, default=0.40, help='Safety cutoff angle (rad)')
    parser.add_argument('--resume-angle', type=float, default=np.radians(4), help='Resume angle (rad)')
    parser.add_argument('--deadzone', type=float, default=0.5)
    parser.add_argument('--threshold', type=float, default=0.5)
    parser.add_argument('--vcap', type=float, default=12.0, help='Proportional voltage cap')
    parser.add_argument('--no-prev-voltage', action='store_true', help='Exclude prev voltage from obs')
    args = parser.parse_args()

    include_prev_voltage = not args.no_prev_voltage

    print("Extracting SAC actor weights...")
    layers = extract_actor_weights(args.model, include_prev_voltage)

    print("\nGenerating C header...")
    generate_header(
        layers, args.output, include_prev_voltage,
        rl_vcap=args.rl_vcap,
        rl_voltage_limit=args.rl_voltage_limit,
        rl_angle_deg=args.rl_angle,
        safe_angle=args.safe_angle,
        resume_angle_rad=args.resume_angle,
        deadzone=args.deadzone,
        threshold=args.threshold,
        vcap=args.vcap,
    )

    # Print memory estimate
    total_floats = sum(w.size + b.size for _, w, b in layers)
    print(f"\n  Memory: {total_floats * 4:,} bytes ({total_floats * 4 / 1024:.1f} KB) for weights")
    print(f"  Stack:  ~{max(w.shape[0] for _, w, b in layers) * 4 * 2 / 1024:.1f} KB for hidden activations")


if __name__ == "__main__":
    main()
