function xdot = furuta_step(x, tau, p)

m  = p.m;
L  = p.L;
l  = p.l;
Ip = p.Ip;
Ia = p.Ia;
g  = p.g;

alpha  = x(1);
a_dot  = x(2);
theta  = x(3);
th_dot = x(4);

tau = max(min(tau, p.umax), -p.umax);

xdot = zeros(4,1);
xdot(1) = a_dot;
xdot(3) = th_dot;

den = (Ip + m*l^2)*(Ia + m*L^2 + m*l^2*sin(theta)^2) ...
    - (m*L*l*cos(theta))^2;

xdot(2) = ( ...
    m*L*l*(th_dot^2)*sin(theta) ...
    + tau ...
    + m*L*l*cos(theta)*( ...
        (m*l^2*a_dot^2*sin(theta)*cos(theta) + m*g*l*sin(theta)) ...
        /(Ip + m*l^2)) ...
    - 2*m*l^2*a_dot*th_dot*sin(theta)*cos(theta) ...
    ) * ((Ip + m*l^2)/den);

xdot(4) = ( ...
    m*l^2*a_dot^2*sin(theta)*cos(theta) ...
    + m*g*l*sin(theta) ...
    - m*L*l*cos(theta)*( ...
        (m*L*l*(th_dot^2)*sin(theta) + tau ...
        - 2*m*l^2*a_dot*th_dot*sin(theta)*cos(theta)) ...
        /(Ia + m*L^2 + m*l^2*sin(theta)^2)) ...
    ) * ((Ia + m*L^2 + m*l^2*sin(theta)^2)/den);

end
